pipeline {
    agent any
    stages {        
        stage('Test') {
            steps {
                script {
                        bat 'mvn verify -Pperformance'
                    }
            }
        }
       
    }
}